### ISSUE TITLE
URGENT! minidlna change user:group of all /var/log

### ISSUE THREAD

**Issue by vpistis** [OpenMediaVault-Plugin-Developers/openmediavault-minidlna#11]
Hi,

I noticed today that all files and directories into `/var/log` have wrong permissions: `minidlna:minidlna`.
If I adjust with `chown` command, after restart minidlna again sets wrong permissions.
At the moment I have disabled the plugin.
Is possible to correct this bug?

tx

**Comment by ryecoaaron** [comment]
Urgent?? Fixed in newest release.

**Comment by vpistis** [comment]
My `nextcloud` instance doesn't start because `redis` server fails to start: permissions for redis log directory are wrong.
My `gitlab` instance is broken for the same reason.
This is the sense of `urgent` for me :)

Thanx a lot for the fix and for your work :)
