### ISSUE TITLE
File name problem:  90openmediavault-minidlna

### ISSUE THREAD

**Issue by adamnagy1** [OpenMediaVault-Plugin-Developers/openmediavault-minidlna#13]
Hello Guys,

One of a Hungarian OMV enthusiast found a problem. As he can't speak English, I try to translate his finding:
"I think there is problem with the file name. I guess it should look like that:
90-openmediavault-minidlna.conf
The problem is in the postinst and postrm scripts. It might be good at install time, when you specifically run sysctl with that parameter, but it won't be loading after a server restart because of the different file name.
Hope that it helps."
 Adam

**Comment by ryecoaaron** [comment]
This is incorrect.  The .conf files in the /etc/sysctl.d/ are processed at boot.  The readme in the directory states:

Files found under the /etc/sysctl.d directory that end with .conf are
parsed within sysctl(8) at boot time.  If you want to set kernel variables
you can either edit /etc/sysctl.conf or make a new file.

The filename isn't important, but don't make it a package name as it may clash
with something the package builder needs later. It must end with .conf though.

**Comment by adamnagy1** [comment]
I'm sorry to take it again, but as you write it: "It must end with .conf though." And now .conf is missing from the scripts, so it will be missed from the filename. Please have a look at the line 60 and 62 in the postinst and the corresponding postrm lines.
Adam

**Comment by ryecoaaron** [comment]
I didn't even notice the .conf extension and wasn't sure what you were pointing out.  Fixed now.  The .conf extension wasn't mandatory when it was added to the plugin.
