### ISSUE TITLE
Support DSD files

### ISSUE THREAD

**Issue by maxengel** [OpenMediaVault-Plugin-Developers/openmediavault-minidlna#15]
It would be great if [these changes](https://sourceforge.net/p/minidlna/discussion/879956/thread/816fde51/) were included to support DSD files.

**Comment by ryecoaaron** [comment]
The plugin uses the minidlna package from the Debian repos.  I don't want to start compiling/maintaining packages.  I suppose you could file a request with Debian to have them include this patch.

**Comment by maxengel** [comment]
It looks like [it was merged into the main branch.](https://sourceforge.net/p/minidlna/git/ci/master/tree/) Hopefully v. 1.2.2 will be released soon with this fix.

**Comment by parkmino** [comment]
Is it possible to upgrade to 1.3.0 which is available for bullseye and sid, not for buster though.
