### ISSUE TITLE
minidlna shows pictures and music even not chosen

### ISSUE THREAD

**Issue by djsmix** [OpenMediaVault-Plugin-Developers/openmediavault-minidlna#17]
<img width="405" alt="Skærmbillede 2021-01-28 kl  21 04 04" src="https://user-images.githubusercontent.com/62570067/106192963-2ac93d00-61ad-11eb-8c86-16886349a92a.png">

![IMG_9518](https://user-images.githubusercontent.com/62570067/106192933-20a73e80-61ad-11eb-8988-b384f1ec99a0.PNG)

Tried to "reset" and deleted the share - and reinstalled the plugin. same issue :(

**Comment by ryecoaaron** [comment]
That is a minidlna problem then.  The plugin can't do anything about it.

**Comment by djsmix** [comment]
> That is a minidlna problem then. The plugin can't do anything about it.

Did i not post the right place?

**Comment by ryecoaaron** [comment]
You posted on the minidlna plugin, yes.  But I can't change how minidlna works.  The omv plugin just configures minidlna.  minidlna is maintained by someone else. https://sourceforge.net/projects/minidlna/

**Comment by ryecoaaron** [comment]
@djsmix did you try changing the "root container"?  Maybe that will do what you want?  I haven't used minidlna in years but the man page describes the root container as:

**Comment by djsmix** [comment]
> @djsmix did you try changing the "root container"? Maybe that will do what you want? I haven't used minidlna in years but the man page describes the root container as:
> 
> root_container
> Use a different container as the root of the tree exposed to clients. The possible
> values
> · ‘.’ to use the standard container (this is the default);
> · ‘B’ to use the “Browse Directory” container;
> · ‘M’ to use the “Music” container;
> · ‘V’ to use the “Video” container;
> · ‘P’ to use the “Pictures” container.
> If you specify ‘B’ and the client device is audio only, then “Music/Folders” will be
> used as the root container.

yup, found out that the "V" where missing, thanks!
