### ISSUE TITLE
Any upgrade plan to 1.3.0

### ISSUE THREAD

**Issue by parkmino** [OpenMediaVault-Plugin-Developers/openmediavault-minidlna#19]
Is there any plan to upgrade to 1.3.0 which is available for bullseye and sid, not for buster though?

**Comment by ryecoaaron** [comment]
The plugin uses whatever version of minidlna is in the Debian repos.  I suggest running minidlna in docker if you need something newer.

**Comment by parkmino** [comment]
FYI, I got bullseye 1.3.0 running after modifying minidlna.service.
