### ISSUE TITLE
[improvement] preselected interface

### ISSUE THREAD

**Issue by coelner** [OpenMediaVault-Plugin-Developers/openmediavault-minidlna#21]
Because of this line:
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-minidlna/blob/1f1e0ea847912c44e926af87e9bd34abf5e4cdca/srv/salt/omv/deploy/minidlna/files/etc-minidlna_conf.j2#L6

the daemon tries to send on all interfaces. This fails, because the second interface is a wireguard endpoint. This inteface is configured baremetal and does not show up in the interface section.
```
minissdp.c:324: error: sendto(udp_notify=10, 10.0.0.5): Required key not available
minissdp.c:324: error: sendto(udp_notify=10, 10.0.0.5): Required key not available
minissdp.c:324: error: sendto(udp_notify=10, 10.0.0.5): Required key not available
```
However, it is easy to activate this setting, but It would be nice if this line is active and prefilled with the interfaces that are configured through omv itself. Or even better, a select button for each interface.

Background: this error message get printed every second and fills up rapidly the folder2ram. This renders the complete system useless until a force shutdown.

**Comment by ryecoaaron** [comment]
I might just add a network interface textinput.  If you leave it blank (default), it will listen on all interfaces.  Otherwise, you can enter a comma separated list of interfaces.  Seriously considering moving this plugin to using docker since it is already written.

**Comment by ryecoaaron** [comment]
This is fixed.  Just waiting a bit for translations.
