### ISSUE TITLE
Log file of MiniDLNA just bomb shelled my root 

### ISSUE THREAD

**Issue by PulsarFX** [OpenMediaVault-Plugin-Developers/openmediavault-minidlna#22]
In a very short period of time the minidlna log file ate up the whole disk space of `/`
```
df -h
Dateisystem    Größe Benutzt Verf. Verw% Eingehängt auf
/dev/sdc1        37G     35G  340M  100% /


ls -l /var/log/minidlna/
insgesamt 30279652
-rw-r--r-- 1 minidlna minidlna 31006314496  3. Nov 22:43 minidlna.log
-rw-r--r-- 1 minidlna minidlna        7552 29. Okt 03:45 minidlna.log.1
-rw-r--r-- 1 minidlna minidlna         214 22. Okt 03:45 minidlna.log.2.gz
-rw-r--r-- 1 minidlna minidlna         330 15. Okt 03:45 minidlna.log.3.gz
-rw-r--r-- 1 minidlna minidlna         988  8. Okt 03:45 minidlna.log.4.gz
```
the content:
```
tail /var/log/minidlna/minidlna.log
minidlna.c:166: error: accept(http): Zu viele offene Dateien   (too many open files)
minidlna.c:166: error: accept(http): Zu viele offene Dateien
minidlna.c:166: error: accept(http): Zu viele offene Dateien
minidlna.c:166: error: accept(http): Zu viele offene Dateien
minidlna.c:166: error: accept(http): Zu viele offene Dateien
minidlna.c:166: error: accept(http): Zu viele offene Dateien
minidlna.c:166: error: accept(http): Zu viele offene Dateien
minidlna.c:166: error: accept(http): Zu viele offene Dateien
minidlna.c:166: error: accept(http): Zu viele offene Dateien
```
and it filled very fast after purging:
```
echo "" >  /var/log/minidlna/minidlna.log
 ls -l /var/log/minidlna/
-rw-r--r-- 1 minidlna minidlna 5844898  3. Nov 22:44 minidlna.log

ls -l /var/log/minidlna/
-rw-r--r-- 1 minidlna minidlna 19963043  3. Nov 22:44 minidlna.log
```
these commands were apart some 10 to 20 seconds. 

After stopping and purging the log, OMV stats showed this:
![grafik](https://user-images.githubusercontent.com/4960210/199844240-b89e19c6-f838-430d-a5f7-335319d3b10b.png)

Is there a way to prevent this from taking down the whole system?

**Comment by ryecoaaron** [comment]
Did you change the log level?

**Comment by PulsarFX** [comment]
No. The log file is flooded with error messages, like shown above: too many open files.

**Comment by ryecoaaron** [comment]
I understand that but the log level on the settings tab of the plugin determines how much is logged. What level is your system set to?

**Comment by PulsarFX** [comment]
Log level is set to error. 
Extra options is empty.
All Checkboxes are off (strict dlna, tivo, wide links)

**Comment by ryecoaaron** [comment]
Seems like minidlna shouldn’t be logging that much. you could turn logging off. Other than changing the log level, there isn’t anything the plugin can do about this.  You could ask on the ReadyMedia forum.
