### ISSUE TITLE
very ressource CPU when minidlna work

### ISSUE THREAD

**Issue by crashcoq** [OpenMediaVault-Plugin-Developers/openmediavault-minidlna#4]
I have installed the plugins minidlna

This service use 75% ressoure CPU always on the system
When i restart the service by command line, ressource cpu down to 15%
I use an base DB on minidlna.conf
the timeout base is 800s

it's normal ?

**Comment by ryecoaaron** [comment]
minidlna does scan your library each time it starts.  That may be causing the high cpu usage.  Does it stay at 75% even after it says it is finished scanning in the log?  What is the output of:  cat /etc/minidlna.conf

**Comment by crashcoq** [comment]
At start the ressource cpu is 82%
After 5 minutes, the ressource is 75% !
I need to restart the service for 15% ressource

**Comment by ryecoaaron** [comment]
I've seen it take much longer than 5 minutes to scan a library especially if it is a large library and/or has bluray rips in it.

You didn't tell me if it said "finished" in the log.  You also didn't post the output of the command I asked for.  Very difficult to determine the problem without this information.

**Comment by crashcoq** [comment]
Hello

my conf:

port=8200
#network_interface=eth0
friendly_name=MiniDLNA Server on OpenMediaVault
db_dir=/media/5e37f1f5-3de6-47b8-adba-9ff574487563/minidlna
#log_dir=/var/log
album_art_names=Cover.jpg/cover.jpg/AlbumArtSmall.jpg/albumartsmall.jpg/AlbumArt.jpg/albumart.jpg/Album.jpg/album.jpg/Folder.jpg/folder.jpg/Thumb.jpg/thumb.jpg
inotify=yes
enable_tivo=no
strict_dlna=no
notify_interval=600
serial=31446138
model_number=1
#root_container=.
log_level=error
media_dir=/media/5e37f1f5-3de6-47b8-adba-9ff574487563/MULTIMEDIA/
media_dir=/media/5e37f1f5-3de6-47b8-adba-9ff574487563/DONNEE/sonia/
media_dir=/media/5e37f1f5-3de6-47b8-adba-9ff574487563/DONNEE/david/
media_dir=/media/5e37f1f5-3de6-47b8-adba-9ff574487563/TEMP/

**Comment by ryecoaaron** [comment]
Maybe the load is higher because you manually moved the location of the database to the same drive with the media on it.  I have never tested this configuration.  Try commenting the db_dir line out to see if the load goes back down.

**Comment by crashcoq** [comment]
Hello

I have tried this.
I have the same problem but that laster longer at 75%
After I have 38%, same with the db_dir activated

**Comment by ryecoaaron** [comment]
I guess you will need to ask the minidlna developer because I don't think this is a problem with the plugin.
https://sourceforge.net/projects/minidlna/
