### ISSUE TITLE
mkv not recognized

### ISSUE THREAD

**Issue by Riquet** [OpenMediaVault-Plugin-Developers/openmediavault-minidlna#5]
Hi, 

MiniDLNA works great (OMV 1.14), but sometimes files were not exposed to client, looking in log I found these entries :
[2015/03/14 20:38:29] metadata.c:700: warn: Opening /media/x/Video/xxxxxxxxxxxxxx.mkv failed! [Input/output error]
[2015/03/14 20:38:29] scanner.c:489: warn: Unsuccessful getting details for /media/x/Video/xxxxxxxxxxxxxx.mkv!

File is OK on many clients on Samba or CIFS, but not working with DLNA ?
The only thing I can suspect is a size more than 16Gb ? (18234813892)

Any Idea to resolve this ?

**Comment by ryecoaaron** [comment]
This is a minidlna issue.  minidlna is known for being picky about media files especially large files.  If you are using an amd64 system, you can try the latest minidlna package I create here - http://omv-extras.org/testing/

**Comment by Riquet** [comment]
I use an HP54L wich is an Amd64 System.
Thanks for link, i will try it as soon as i can an tell you if it works for these files.

**Comment by Riquet** [comment]
Hi trying to update from OMV, but I get this error :

Failed to execute command 'export LANG=C; apt-get update 2>&1': E: Type 'http://omv-extras.org/testing/minidlna_1.1.4-omv1_amd64.deb' is not known on line 3 in source list /etc/apt/sources.list.d/omv-extras-org-custom.list E: The list of sources could not be read.

**Comment by ryecoaaron** [comment]
The link doesn't go in the Custom repo tab of omv-extras.  You login as root locally or over ssh and do:

wget http://omv-extras.org/testing/minidlna_1.1.4-omv1_amd64.deb
dpkg -i minidlna_1.1.4-omv1_amd64.deb

**Comment by Riquet** [comment]
update is better with your commands !

But after restart dlna and also OMV, I let a few minutes for database rebuild, and mkv still not listed...
Strange when looking into log...
[2015/03/17 21:34:57] minidlna.c:943: error: MiniDLNA is already running. EXITING

Perhaps, the second update is not working because OMV integrated minidlna still running ?
Any idea ?

**Comment by ryecoaaron** [comment]
If you are getting that error, try rebooting.
