### ISSUE TITLE
"received signal 15, good-bye"

### ISSUE THREAD

**Issue by forsaken006** [OpenMediaVault-Plugin-Developers/openmediavault-minidlna#6]
I get this in my log and from what I have learned from google searches it is stopping miniDLNA. I am having issues with streaming to my samsung smart tv. It will stream from anywhere between 5-45 minutes then the service stops. I have to wait for it to start again and show up in my tv's sources list.

**Comment by ryecoaaron** [comment]
minidlna 1.1.4 in testing repo now.
