### ISSUE TITLE
inotify warning in log

### ISSUE THREAD

**Issue by forsaken006** [OpenMediaVault-Plugin-Developers/openmediavault-minidlna#7]
inotify.c:198: warn: WARNING: Inotify max_user_watches [8192] is low or close to the number of used watches [550] and I do not have permission to increase this limit.  Please do so manually by writing a higher value into /proc/sys/fs/inotify/max_user_watches.

What does this mean / do? 

When i nano /proc/sys/fs/inotify/max_user_watches there is only the value stated "8192"

**Comment by forsaken006** [comment]
I changed the value to 58192.

**Comment by ryecoaaron** [comment]
The plugin is supposed to change it to 100000 when installing.
