### ISSUE TITLE
New options support

### ISSUE THREAD

**Issue by mbaxr** [OpenMediaVault-Plugin-Developers/openmediavault-minidlna#8]
Hi in latest Minidilna present where added some new configuration not yet supported by OVM configuration panel.

http://sourceforge.net/p/minidlna/git/ci/master/tree/minidlna.conf

It should be useful to add at least 

force_sort_criteria

This setting will help people with panasonc Viera devices to set navigate files with different sorting.
Thanks

**Comment by ryecoaaron** [comment]
It will have to be added to the OMV 3.x version of the plugin.

**Comment by ryecoaaron** [comment]
Fixed in 3.1.  You will have to add it to the extra options field.
