### ISSUE TITLE
Advanced/personnal options field

### ISSUE THREAD

**Issue by Fuli10** [OpenMediaVault-Plugin-Developers/openmediavault-minidlna#9]
Hello,

In case of using of own build version of minidlna (with transcode version for example), it can implement new/unknown options.
Can you please add a button for advanced options that enable a text field where we can put own options to write in minidlna.conf file ?
Thanks

**Comment by ryecoaaron** [comment]
I will add it to OMV 3.x version of the plugin.

**Comment by ryecoaaron** [comment]
Fixed in 3.1
